version: 4.5.{build}

branches:
  only:
    - master

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: build.cmd appveyor

test: off

on_success:
  - ps: .\tools\publish-site.ps1
  - ps: .\tools\gh-pages.ps1 -action publish -env appveyor

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL
